import type { Metadata } from 'next';
import './[locale]/globals.css';
import { Nobile, JetBrains_Mono } from 'next/font/google';
import Header from './[locale]/components/Header';
import { NextIntlClientProvider, useLocale } from 'next-intl';

const nobile = Nobile({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-sans',
});

const jetbrainsMono = JetBrains_Mono({
  weight: ['400', '500'],
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const locale = useLocale();

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${nobile.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <head>
        {/* <script
          dangerouslySetInnerHTML={{
            __html: `
        try {
          const t = localStorage.getItem('theme');
          const system = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
          document.documentElement.setAttribute('data-theme', t || system);
        } catch (e) {}
      `,
          }}
        /> */}
      </head>

      <body
        dir={locale === 'ar' ? 'rtl' : 'ltr'}
        className="bg-bg flex min-h-full flex-col font-sans"
      >
        <Header />
        <main>
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </main>
      </body>
    </html>
  );
}
