import type { Metadata } from 'next';
import './globals.css';
import { Nobile, JetBrains_Mono, Cairo } from 'next/font/google';
import Header from './components/Header';
import { hasLocale, NextIntlClientProvider, useLocale } from 'next-intl';
import ToggleLang from './components/ToggleLang';
import { ThemeProvider } from 'next-themes';
import { routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';
import BlobBg from './components/BlobBg';

const cairo = Cairo({
  subsets: ['arabic'],
  variable: '--font-arabic',
});

const nobile = Nobile({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-sans',
});

const jetbrainsMono = JetBrains_Mono({
  weight: ['400', '500'],
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) notFound();

  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className={`${nobile.variable} ${jetbrainsMono.variable} ${cairo.variable} h-full antialiased`}
    >
      <body
        dir={locale === 'ar' ? 'rtl' : 'ltr'}
        className="bg-bg flex min-h-full flex-col overflow-x-hidden"
      >
        <NextIntlClientProvider>
          <ThemeProvider>
            <BlobBg />
            <Header />
            <main>{children}</main>
            <ToggleLang />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
